-- ========================================================
-- Supabase Database Schema for EL Journal Blog
-- ========================================================

-- Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  slug VARCHAR(255) NOT NULL UNIQUE,
  color VARCHAR(50) DEFAULT '#E55B44',
  count INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. POSTS TABLE
CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  slug VARCHAR(500) NOT NULL UNIQUE,
  summary TEXT,
  content TEXT NOT NULL,
  cover_image TEXT,
  category VARCHAR(255) DEFAULT 'Information Assurance',
  author VARCHAR(255) DEFAULT 'Ely',
  read_time VARCHAR(50) DEFAULT '5 min read',
  status VARCHAR(50) DEFAULT 'Published', -- 'Published' or 'Draft'
  featured BOOLEAN DEFAULT FALSE,
  is_latest BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  published_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PROFILES / ADMIN TABLE
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  full_name VARCHAR(255) DEFAULT 'Elyssa Contreras',
  avatar_url TEXT,
  role VARCHAR(50) DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- INDEXES FOR FAST PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_posts_status ON public.posts(status);
CREATE INDEX IF NOT EXISTS idx_posts_slug ON public.posts(slug);
CREATE INDEX IF NOT EXISTS idx_posts_category ON public.posts(category);
CREATE INDEX IF NOT EXISTS idx_posts_featured ON public.posts(featured);

-- AUTOMATIC UPDATED_AT TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_posts_updated_at
BEFORE UPDATE ON public.posts
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- ========================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ========================================================

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- PUBLIC READ ACCESS FOR PUBLISHED POSTS & CATEGORIES
CREATE POLICY "Public users can view published posts"
ON public.posts FOR SELECT
USING (status = 'Published' OR auth.role() = 'authenticated');

CREATE POLICY "Public users can view categories"
ON public.categories FOR SELECT
USING (true);

CREATE POLICY "Public users can view author profiles"
ON public.profiles FOR SELECT
USING (true);

-- ADMIN FULL ACCESS FOR AUTHENTICATED USERS
CREATE POLICY "Admin full access on posts"
ON public.posts FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin full access on categories"
ON public.categories FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin full access on profiles"
ON public.profiles FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

-- ========================================================
-- INITIAL SEED DATA
-- ========================================================
INSERT INTO public.categories (name, slug, color, count) VALUES
('Information Assurance', 'information-assurance', '#E55B44', 1),
('Organizational Context', 'organizational-context', '#F59E0B', 0),
('Computing Ethics', 'computing-ethics', '#8B5CF6', 0),
('Data Privacy', 'data-privacy', '#3B82F6', 0),
('Security Principles', 'security-principles', '#10B981', 0),
('Others', 'others', '#6B7280', 0)
ON CONFLICT (name) DO NOTHING;
